---
title: "MT5763: 1st Assignment"
output:
  pdf_document: default
  html_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Report by 210034046

```{r MY Assignment, echo=TRUE}
<<<<<<< HEAD
#importing tidyverse for cleaning our data and lubridate for date functions
=======
#importing tidyverse for cleaning our data
#importing tidyverse for cleaning our data
library(tidyverse)
library(lubridate)
#reading csv file for bikeseoul dataset
bike_seoul <- read_csv('BikeSeoul.csv')

#Bike Seoul Data Wrangling/Cleaning
bike_seoul <-
  bike_seoul %>% select(-starts_with("Visibility"),-starts_with("Dew"),
                        -starts_with("Solar"),-starts_with("Rain"),
                        -starts_with("Snow")) %>%
  #removing columns for visibility, dew point temperature, solar radiation, rainfall and snowfall.
  filter(`Rented Bike Count` != 0) %>% 
  #filtering out where no data was collected for bike count
  select(-'Functioning Day') %>% 
  #removing functioning day column
  rename(Date = Date, Count = "Rented Bike Count",Hour = "Hour",
         Temperature = "Temperature(C)",Humidity = "Humidity(%)",
         WindSpeed = "Wind speed (m/s)",Season = "Seasons", Holiday = "Holiday") %>% 
  #renaming columns
  mutate(Date = as.Date(Date, tryFormats = c("%d-%m-%Y", "%d/%m/%Y"))) %>%
  # Converting Date to date object
mutate(FullDate = make_datetime(day = day(Date),month = month(Date),
                                year = year(Date),hour = Hour)) %>% 
  #a new column is added, called FullDate which includes the hour in it
  mutate(Holiday = factor(Holiday,levels = c('Holiday', 'No Holiday'),
                          labels = c('Yes', 'No'))) %>% 
  #Holiday factor level changed to Yes/No
  mutate(Season = factor(Season, levels = c("Spring", "Summer",
                                            'Autumn', 'Winter')))
#Factor order level changed for Season as specified i.e Spring, Summer, Autumn and Winter

bike_washington<-read_csv('BikeWashingtonDC.csv')

<<<<<<< HEAD
bike_washington<-bike_washington%>%
#Removing columns: instant, yr, mnth, weekday,
#workingday, weathersit, atemp, casual and reg.
=======
bike_washington<-bike_washington%>%#Removing columns: instant, yr, mnth, weekday, workingday, weathersit, atemp, casual and registered users
>>>>>>> 3c6bfdad6a5a48336c9d01866436ca4ecbe32859
  select(-"instant",-"yr",-"mnth",
         -"weekday",-"workingday",
         -"weathersit",-"atemp",-"casual",-"registered")%>%
  #removing columns
  rename(Date = 'dteday',Count = "cnt", Hour = "hr",
         Temperature = "temp", Humidity = "hum",
         WindSpeed = "windspeed",Season = "season", 
         Holiday = "holiday" )%>%#renaming columns
  mutate(Season = factor(Season, levels = c("1", "2",
                                            '3', '4'),
                         labels = c("Winter","Spring","Summer","Autumn")))%>%
  #changing factor levels of seasons
  mutate(Season = factor(Season, 
                         levels = c("Spring", "Summer",
                                    'Autumn', 'Winter')))%>%
  #ordering them the same way as in seoul dataset
  mutate(Date = as.Date(Date, tryFormats = c("%d-%m-%Y", "%d/%m/%Y")))%>% 
  #converting date to date object
  mutate(Holiday = factor(Holiday,levels = c('1', '0'),
                          labels = c('Yes', 'No')))%>%
  #changing Holiday factors to YES/NO
  mutate(FullDate = make_datetime(day = day(Date),
                                  month = month(Date),year = year(Date),
                                  hour = Hour))#adding Fulldate column
bike_washington$Humidity<-sapply(bike_washington$Humidity,
                                 function(vec,n){return(vec*n) },
                                 n=100)#scaling humidity by multiplying it by 100
bike_washington$WindSpeed<-sapply(bike_washington$WindSpeed,
                                  function(vec,n){return(vec*n)},
                                  n=(67000/(60*60)))
#scaling windspeed by multiplying it by 67000/3600(67km/hr) to get it in m/s

#Visualization Part

#Seoul dataset visulization
<<<<<<< HEAD
ggplot(bike_seoul)+
  geom_point(aes(x=Date,y=Temperature,colour=Season))+
  ggtitle("Plot Temperature over time: Seoul")
#the visualization shows the pattern of temperature rise and fall throughout the year.

ggplot(bike_seoul)+
  geom_point(aes(x=Date,y=Temperature,colour=Season))+
  facet_wrap(~Season)+
  ggtitle("Plots for Each Season's temperature Seperated: Seoul")
#Temperatures of different seasons seperated.

ggplot(bike_seoul)+
  geom_point(aes(x=Holiday,y=Count,colour=Holiday))+
  ggtitle("Plot for Holiday/Non-holiday bike count: Seoul")
#Holiday and No holiday count shows more bikes rented on working days.

ggplot(bike_seoul)+
  geom_point(aes(x=Hour,y=Count,colour=Temperature))+
ggtitle("Plot for hourly rented bike count: Seoul")
#The peak time for renting bike is shown around 8 am and 2-9 pm.

ggplot(bike_seoul)+
  geom_point(aes(x=Temperature,y=Count))+
  stat_smooth(aes(x=Temperature,y=Count),method="lm")+
  ggtitle("Plot for Temperature vs Rented bikes: Seoul")
#Shows increase in bikes rented as temperature rises.

ggplot(bike_seoul)+
  geom_point(aes(x=WindSpeed,y=Count))+
  stat_smooth(aes(x=WindSpeed,y=Count),method="lm")+
  ggtitle("Plot for WindSpeed vs Rented bike count: Seoul")
#Shows increase in bikes rented in windy condition.

ggplot(bike_seoul)+
  geom_point(aes(x=Humidity,y=Count))+
  stat_smooth(aes(x=Humidity,y=Count),method = "lm")+
  ggtitle("Plot for Humidity Vs Rented bike count: Seoul")
#Strong decrease in rented bikes with increased humidity

#Washington dataset visualization

ggplot(bike_washington)+
  geom_point(aes(x=Date,y=Temperature,colour=Season))+
  ggtitle("Plot Temperature over time: Washington")
#Shows the pattern of temperature rise and fall throughout the year in Washington.
=======
ggplot(bike_seoul)+#the visualization showing pattern of temperature throughout the year.
  geom_point(aes(x=Date,y=Temperature,colour=Season))+
  ggtitle("Plot Temperature over time: Seoul")

ggplot(bike_seoul)+
  geom_point(aes(x=Date,y=Temperature,colour=Season))+#Temperatures of different seasons seperated.
  facet_wrap(~Season)+
  ggtitle("Plots for Each Season's temperature Seperated: Seoul")
ggplot(bike_seoul)+#Holiday and No holiday count shows more bikes rented on working days.
  geom_point(aes(x=Holiday,y=Count,colour=Holiday))+
  ggtitle("Plot for Holiday/Non-holiday bike count: Seoul")
ggplot(bike_seoul)+#the peak time for renting bike was shown around 8 am and 2-9 pm.
  geom_point(aes(x=Hour,y=Count,colour=Temperature))+
ggtitle("Plot for hourly rented bike count: Seoul")
ggplot(bike_seoul)+geom_point(aes(x=Temperature,y=Count))+stat_smooth(aes(x=Temperature,y=Count),method="lm")+#Shows increase in bikes rented as temperature rises.
  ggtitle("Plot for Temperature vs Rented bikes: Seoul")
ggplot(bike_seoul)+geom_point(aes(x=WindSpeed,y=Count))+stat_smooth(aes(x=WindSpeed,y=Count),method="lm")+#A slight slope shows there is some increase in bikes rented in breezy (windy) condition.
  ggtitle("Plot for WindSpeed vs Rented bike count: Seoul")
ggplot(bike_seoul)+geom_point(aes(x=Humidity,y=Count))+stat_smooth(aes(x=Humidity,y=Count),method = "lm")+#Strong decrease in rented bikes with increased humidity
  ggtitle("Plot for Humidity Vs Rented bike count: Seoul")



#Washington dataset visualization
ggplot(bike_washington)+#the visualization shows the pattern of temperature rise and fall throughout the year in Washington.
  geom_point(aes(x=Date,y=Temperature,colour=Season))+
  ggtitle("Plot Temperature over time: Washington")
>>>>>>> 3c6bfdad6a5a48336c9d01866436ca4ecbe32859

ggplot(bike_washington)+
  geom_point(aes(x=Date,y=Temperature,colour=Season))+
  facet_wrap(~Season)+
  ggtitle("Plots for Each Season's temperature Seperated: Washington")
<<<<<<< HEAD
#Temperatures of different seasons seperated.

ggplot(bike_washington)+
  geom_point(aes(x=Holiday,y=Count,colour=Holiday))+
  ggtitle("Plot for Holiday vs Non-holiday bike count: Washington")
#Seoul alike, Holiday VS No holiday bike rented count shows more bikes rented on working days.

ggplot(bike_washington)+
  geom_point(aes(x=Hour,y=Count,colour=Temperature))+
  ggtitle("Plot for hourly rented bike count: Washington")
#Peak times for renting a bike is around 7 or 8 am and stays high from 12-6 pm.

ggplot(bike_washington)+
  geom_point(aes(x=Temperature,y=Count))+
  stat_smooth(aes(x=Temperature,y=Count),method="lm")+
  ggtitle("Plot for Temperature vs Rented bikes: Washington")
#Similar to Seoul, shows increase in bikes rented as temperature rises.

ggplot(bike_washington)+geom_point(aes(x=WindSpeed,y=Count))+
  stat_smooth(aes(x=WindSpeed,y=Count),method="lm")+
  ggtitle("Plot for WindSpeed vs Rented bike count: Washington")
#Again similar to Seoul's, slight increase in bikes rented as it gets more windy.

ggplot(bike_washington)+geom_point(aes(x=Humidity,y=Count))+
  stat_smooth(aes(x=Humidity,y=Count),method = "lm")+
  ggtitle("Plot for Humidity vs Rented bike count: Seoul")
#Sharper decrease in rented bikes than Seoul with humidity increase.

##STATISCAL MODELLING

#Bike Seoul Model

bike_seoul$LoggedCount<-log(bike_seoul$Count)
#log count as outcome

seoul_model<-lm(LoggedCount~Season+Temperature+Humidity+WindSpeed,data=bike_seoul)
#predictors are season, temperature, humidity windspeed
summary(seoul_model)
#It shows that the predictors Autumn, Winter, Temperature, 
#Humidity and windspeed, have significance.
#Therefore, rejects the null hypothesis, of them being equal to zero.

confint(seoul_model,level = 0.97)
#97% confidence intervals for the estimated regression co-efficients, 
#they are reliable as sample size is large 8465 and there have low variance.

df_pred<-data.frame(Season="Winter",Temperature=0,WindSpeed=0.5,Humidity=20)
#values for the model's prediction to be based upon.

predict(seoul_model,newdata = df_pred)
#5.913 bikes rented in Seoul

predict(seoul_model,newdata = df_pred,interval = "prediction",level = 0.90)
#Therefore, we are (90%) confident with the given parameters, 
#would at least rent 4.55 bikes and at maximum 7.28 bikes.

#Bike Washington Model
bike_washington$LoggedCount<-log(bike_washington$Count)
washington_model<-lm(LoggedCount~Season+Temperature+Humidity+WindSpeed,data=bike_washington)

summary(washington_model)
#In Washington the predictors, Summer,Autumn, Winter, temperature, 
#Humidity and Wind speed all have significance, 
#rejecting the null hypothesis of them being zero.

confint(washington_model,level = 0.97)
#As we have quite a large sample size of 17379, 
#the confidence intervals for the co-efficient are reliable and low variance. 

predict(washington_model,newdata = df_pred)
#3.64 bikes rented in Washington

predict(washington_model,newdata = df_pred,interval = "prediction",level = 0.90)
#Therefore, we are (90%) confident with the given parameters,
#would at least rent 1.55 bikes and at maximum 5.71 bikes.
=======
ggplot(bike_washington)+#Similar to Seoul, Holiday and No holiday bike rented count shows more bikes rented on working days.
  geom_point(aes(x=Holiday,y=Count,colour=Holiday))+
  ggtitle("Plot for Holiday/Non-holiday bike count: Washington")
ggplot(bike_washington)+geom_point(aes(x=Hour,y=Count,colour=Temperature))+
  ggtitle("Plot for hourly rented bike count: Washington")
#Peak times for renting a bike is around 7 or 8 am and stays high from 12-6 pm.
ggplot(bike_washington)+geom_point(aes(x=Temperature,y=Count))+stat_smooth(aes(x=Temperature,y=Count),method="lm")+
  ggtitle("Plot for Temperature vs Rented bikes: Washington")
#Similar to Seoul, shows increase in bikes rented as temperature rises.
ggplot(bike_washington)+geom_point(aes(x=WindSpeed,y=Count))+stat_smooth(aes(x=WindSpeed,y=Count),method="lm")+
  ggtitle("Plot for WindSpeed vs Rented bike count: Washington")
#Again similar to Seoul's, slight slope shows there is some increase in bikes rented in breezy (windy) condition.
ggplot(bike_washington)+geom_point(aes(x=Humidity,y=Count))+stat_smooth(aes(x=Humidity,y=Count),method = "lm")+
  ggtitle("Plot for Humidity Vs Rented bike count: Seoul")
#Sharper decrease in rented bikes than Seoul as humidity rises.

bike_seoul$LoggedCount<-log(bike_seoul$Count)#log count as outcome
seoul_model<-lm(LoggedCount~Season+Temperature+Humidity+WindSpeed,data=bike_seoul)
#predictors are season, temperature, humidity windspeed
confint(seoul_model,level = 0.97)
#97% confindence intervals for the estimated regression coeffeicients
df_pred<-data.frame(Season="Winter",Temperature=0,WindSpeed=0.5,Humidity=20)
#values for the model's prediction to be based upon.
predict(seoul_model,newdata = df_pred)
#5.913 bikes rented in seoul
predict(seoul_model,newdata = df_pred,interval = "prediction",level = 0.90)
#lower 4.55126561 and Upper 7.275 prediction intervals

bike_washington$LoggedCount<-log(bike_washington$Count)
washington_model<-lm(LoggedCount~Season+Temperature+Humidity+WindSpeed,data=bike_washington)
confint(washington_model,level = 0.97)
df_pred<-data.frame(Season="Winter",Temperature=0,WindSpeed=0.5,Humidity=20)
predict(washington_model,newdata = df_pred)
#3.63 bikes rented in washington
predict(washington_model,newdata = df_pred,interval = "prediction",level = 0.90)
#lower and upper prediction intervals


```
>>>>>>> 3c6bfdad6a5a48336c9d01866436ca4ecbe32859



<<<<<<< HEAD


=======
>>>>>>> 3c6bfdad6a5a48336c9d01866436ca4ecbe32859
